coverage:
  status:
    project:
      default:
        target: auto       # use current base as reference
        threshold: 2%      # allow up to 2% drop without failing
    patch:
      default:
        threshold: 2%
